---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(metaUI)
library(dplyr)
```


## Preparing data

If you have the data prepared for metaUI, you can read it in directly with `import_data()`. If any preprocessing needs to be done (e.g., for labels), you can also read in the file, preprocess it and then pass it to `import_data()`.

```{r}
df <- read.csv(system.file("extdata", "barroso2021.csv", package = "metaUI"))

df <- df %>% mutate(
  study_label = paste0(author, " (", pub_year, ")", ": ", study_id),
  se = sqrt(vi), p.value = 2 * pnorm(-abs(yi)),
  continent = factor(continent) %>% 
    forcats::fct_recode("North America" = "1", "South America" = "2", "Europe" = "3",
                        "Asia" = "4", "Africa" = "5", "Oceania" = "6", "NA" = "-999"),
  teachers = factor(teachers) %>% 
    forcats::fct_recode(yes = "1", no = "2")
)

df <- prepare_data(df,
  study_label = "study_label", es_field = "yi", se = "se", pvalue = "p.value",
  sample_size = "ni",
  variance = "vi", 
  filters = c("Publication Year" = "pub_year", Continent = "continent", "Teacher Sample" = "teachers"), 
  es_type = "SMD"
)
```

## Running the app

```{r eval = FALSE}
generate_shiny(df, "Barroso et al 2021 - Maths Anxiety", "Fisher's Z scores")
```

## Saving the app

```{r eval=FALSE}
generate_shiny(df, "Barroso et al 2021 - Maths Anxiety", "Fisher's Z scores", save_to_folder = "my_app")
```

